### PR TITLE
1.1.0 - Bump dependencies versions and clean.

### PR DESCRIPTION
**Pull request by jeremyzahner**
* Bumped loader-utils to new version.
* Bumped nunjucks to new version.
* Added Changelog.
* Added version 1.1.0.

### CODE REVIEW

**Comment by ryanhornberger** [comment]
Hey Jeremy! Thanks for submitting a PR. I don't really use this module myself anymore. If you are making active use of it and would like to own the module I'd love to discuss.

**Comment by jeremyzahner** [comment]
@ryanhornberger that sounds pretty good! I would like that. You can find me on npm under the same name! :-)

**Comment by jeremyzahner** [comment]
@ryanhornberger Ping. Could you release the new version (properly tagged) to npm or add me as a member (here and on npm)? =) Thanks!

**Comment by jeremyzahner** [comment]
@ryanhornberger Ping. =)

**Pull request merged**
